CREATE ROLE posterr WITH
	LOGIN
	NOSUPERUSER
	CREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'xxxxxx';

CREATE DATABASE posterr
  WITH
  OWNER = posterr
  ENCODING = 'UTF8'
  CONNECTION LIMIT = -1;
